#cloud-config
rancher:
  services_include:
    rancher-server: true
  docker:
    extra_args:
      - -H
      - tcp://0.0.0.0:2375
  network:
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
    interfaces:
      eth0:
        dhcp: true
      eth1:
        address: 192.168.56.10/24
        dhcp: false
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8KkqgSbrPARvkw6QU/wS6wDR2vR5H5OZ20jVR2GFh4po8DOq0f1xdajjGnF6wgvKeOBgWgPUjjS/npbCAk3xfLLF36JImLbqX9n3sONKaFRU6ISEZd/1qVLcQYarKLUrs2vfQBoLj1cxLNtChNV243Uxr/kb2dMrSluq6xqDOqem6RF6ayDc5RDN/8lyBFcSkT7LePBu8caaJ/q4uo1y02Bu/haa14Rojxur3I++0KcbaOQc0+v/Q3ghIY0PKmzqqw1N+rPJ7pU9gUPqsDbTz4TjQvjJFCpvlB0ur7P/syomVQecDVtmB0HtBUKv2UYxIp1laNfdyBkwCKPLolJmLeLfc+gXo9oMYI39gwY0L5MIeOQxhQsPH4brrMuNr23giD+IQ9NpwvcQmoEzK+/oZpsz1iIXRBle+2IaXB8EaDhnuZcFPDUyEa0YomhKeoQnrgKaqWshYH4IQVAOHmvjK95HEZSzpAggJArtu+Z5ZEgURaTzy+9LiPZBjCwzG2vPYf3AyXrBcpyC4b5K6s74UX8CVCytT/dX44CWB28QfW/V4+lv6Z7qkh63ILMr5fVXFjlreOFtqFu7pHY7gast4ag1UkPbaQ7pRnF/bsagHj9DpmpX4bGHY6h2IioI/oLrhkcpe0rFvZWrOCOKjQnvENStSVEAwMFRrXTxuhwAtUQ== mail@maymarcus.de
